import { Button } from '@/shared/ui/Button'
import { useToast } from '@/shared/ui/Toast'
import { Copy, ExternalLink, Globe } from 'lucide-react'
import { tenantHost, tenantUrl } from '../lib/tenant'

/**
 * The organization's code and own address (ADR 0022): open it or copy it.
 * The code is generated by the database and never changes.
 */
export function SubdomainBar({ code }: { code: string }) {
  const { show } = useToast()
  const url = tenantUrl(code)
  return (
    <div className="mb-4 flex flex-wrap items-center gap-2 rounded-xl border border-console-700 bg-console-900 px-3 py-2.5">
      <Globe size={15} className="shrink-0 text-brasa-400" aria-hidden />
      <span className="font-mono text-sm font-semibold tracking-widest text-neutral-50">{code}</span>
      <span className="min-w-0 flex-1 truncate font-mono text-sm text-neutral-400">{tenantHost(code)}</span>
      {url && (
        <a
          href={url}
          target="_blank"
          rel="noopener noreferrer"
          className="inline-flex h-8 items-center gap-1.5 rounded-lg border border-console-700 px-3 text-xs font-medium text-neutral-200 hover:bg-console-800"
        >
          <ExternalLink size={13} aria-hidden /> Abrir organización
        </a>
      )}
      <Button size="sm" variant="secondary" icon={Copy} onClick={() => void navigator.clipboard.writeText(url ?? code).then(() => show('Dirección copiada.'))}>
        Copiar
      </Button>
    </div>
  )
}
