-- ADR 0022: a 6-character tenant code is the subdomain of each organization
-- (replaces the name-based slug of ADR 0021, D1).
--
--   * Generated in the database at creation (dk_new_tenant_code): alphabet
--     without confusable characters (no 0/O, 1/I/L), at least one letter and
--     one digit (never a word), not reserved, globally unique.
--   * Concurrency: generation takes a transaction-level advisory lock, so two
--     simultaneous creations wait for each other and cannot pick the same
--     code; UNIQUE stays as the last guard.
--   * Immutable for everyone, for the whole life of the organization.
--   * The slug stays as internal data (/o/{slug} paths), never a subdomain:
--     the alias table and the "change subdomain" function go away (both
--     unused: no alias was ever created).

-- ---------------------------------------------------------------------------
-- 1. The code
-- ---------------------------------------------------------------------------
create or replace function dk_new_tenant_code()
returns text
language plpgsql
volatile
security definer
set search_path = public, extensions
as $$
declare
  v_alphabet constant text := '23456789ABCDEFGHJKMNPQRSTUVWXYZ';
  v_bytes bytea;
  v_code text;
begin
  -- One creation at a time picks a code (released at commit): no race between two sign-ups.
  perform pg_advisory_xact_lock(hashtext('dk_new_tenant_code'));
  loop
    v_bytes := gen_random_bytes(6);
    v_code := '';
    for i in 0..5 loop
      v_code := v_code || substr(v_alphabet, (get_byte(v_bytes, i) % 31) + 1, 1);
    end loop;
    continue when v_code !~ '[A-Z]' or v_code !~ '[0-9]';
    continue when dk_is_reserved_slug(v_code);
    exit when not exists (select 1 from dk_organizations where tenant_code = v_code);
  end loop;
  return v_code;
end;
$$;

revoke execute on function dk_new_tenant_code() from public, anon, authenticated;

alter table dk_organizations add column tenant_code text;

-- Existing organizations get theirs (one by one, so each sees the previous).
do $$
declare v_id uuid;
begin
  for v_id in select id from dk_organizations where tenant_code is null order by created_at loop
    update dk_organizations set tenant_code = dk_new_tenant_code() where id = v_id;
  end loop;
end $$;

alter table dk_organizations alter column tenant_code set not null;
alter table dk_organizations add constraint dk_organizations_tenant_code_key unique (tenant_code);
alter table dk_organizations add constraint dk_organizations_tenant_code_format
  check (tenant_code ~ '^[2-9A-HJKMNP-Z]{6}$' and tenant_code ~ '[A-Z]' and tenant_code ~ '[0-9]');
comment on column dk_organizations.tenant_code is 'ADR 0022: código público de 6 caracteres; subdominio {código}.quanela.com. Lo genera la base y es inmutable.';

create or replace function dk_assign_tenant_code()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  -- Always generated by the database: a value sent by a client is ignored.
  new.tenant_code := dk_new_tenant_code();
  return new;
end;
$$;

create trigger dk_trg_organizations_tenant_code before insert on dk_organizations
  for each row execute function dk_assign_tenant_code();

-- ---------------------------------------------------------------------------
-- 2. Immutable code and slug (the guard of ADR 0008/0021, without the slug-change path)
-- ---------------------------------------------------------------------------
create or replace function dk_guard_organization()
returns trigger
language plpgsql
set search_path to 'public'
as $function$
begin
  -- ADR 0022: the tenant code never changes, for anyone (migrations included would have to drop this trigger).
  if new.tenant_code is distinct from old.tenant_code then
    raise exception 'El código de la organización no se puede cambiar';
  end if;
  if auth.uid() is null then
    return new;
  end if;
  if new.owner_user_id is distinct from old.owner_user_id then
    raise exception 'El SUPER_ADMIN (creador de la organización) es intransferible';
  end if;
  if new.slug is distinct from old.slug then
    raise exception 'El identificador interno de la organización no se puede cambiar';
  end if;
  if dk_is_superadmin() then
    return new;
  end if;
  if new.active is distinct from old.active and old.owner_user_id is distinct from dk_current_profile_id() then
    raise exception 'Solo el SUPER_ADMIN puede activar o desactivar la organización';
  end if;
  if new.max_accounts is distinct from old.max_accounts then
    raise exception 'El tope de Cuentas lo fija la plataforma';
  end if;
  return new;
end;
$function$;

-- ---------------------------------------------------------------------------
-- 3. Name-based subdomains go away (D3)
-- ---------------------------------------------------------------------------
drop function dk_ga_set_organization_slug(uuid, text);

create or replace function dk_unique_slug(p_base text, p_table text)
returns text
language plpgsql
stable
security definer
set search_path to 'public'
as $function$
declare
  v_slug text := p_base;
  v_n int := 1;
  v_taken boolean;
begin
  loop
    if p_table = 'kitchens' then
      select exists (select 1 from dk_kitchens where slug = v_slug) into v_taken;
    else
      select dk_is_reserved_slug(v_slug) or exists (select 1 from dk_organizations where slug = v_slug) into v_taken;
    end if;
    exit when not v_taken;
    v_n := v_n + 1;
    v_slug := left(p_base, 55) || '-' || v_n;
  end loop;
  return v_slug;
end;
$function$;

drop table dk_organization_slug_aliases;

-- ---------------------------------------------------------------------------
-- 4. Public resolution by code (anonymous; no ids, no other data)
-- ---------------------------------------------------------------------------
drop function dk_tenant_public(text);

create or replace function dk_tenant_public(p_code text)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_code text := upper(btrim(coalesce(p_code, '')));
  v_org dk_organizations;
begin
  if v_code !~ '^[2-9A-HJKMNP-Z]{6}$' then
    return jsonb_build_object('exists', false);
  end if;
  select * into v_org from dk_organizations where tenant_code = v_code;
  if not found then
    return jsonb_build_object('exists', false);
  end if;
  return jsonb_build_object('exists', true, 'code', v_org.tenant_code, 'name', v_org.name, 'active', v_org.active);
end;
$$;

grant execute on function dk_tenant_public(text) to anon, authenticated;

-- ---------------------------------------------------------------------------
-- 5. The code travels with the organization: context of the person and portal
--    (same bodies as before, plus tenantCode).
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.dk_my_context()
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_user dk_users;
  v_platform boolean := dk_is_superadmin();
begin
  select * into v_user from dk_users where auth_user_id = auth.uid();
  if not found then return null; end if;

  return jsonb_build_object(
    'profile', jsonb_build_object(
      'id', v_user.id, 'fullName', v_user.full_name, 'avatarKey', v_user.avatar_key,
      'active', v_user.active, 'isPlatformAdmin', v_platform, 'lastAccountId', v_user.last_account_id),
    'accountPermissions', (select coalesce(jsonb_agg(p.key order by p.sort_order), '[]') from dk_permissions p where p.scope = 'account'),
    'organizations', coalesce((
      select jsonb_agg(jsonb_build_object(
          'id', o.id, 'slug', o.slug, 'tenantCode', o.tenant_code, 'name', o.name, 'active', o.active,
          'isOwner', o.owner_user_id = v_user.id,
          'isSuperAdmin', v_platform or coalesce(om.is_super_admin and om.status = 'active', false),
          'status', coalesce(om.status, 'active'),
          'permissions', (select coalesce(jsonb_agg(p.key order by p.sort_order), '[]') from dk_permissions p
                          where p.scope = 'organization' and dk_has_org_permission(o.id, p.key)))
        order by o.name)
      from dk_organizations o
      left join dk_organization_members om on om.organization_id = o.id and om.user_id = v_user.id
      where v_platform or om.user_id is not null
    ), '[]'),
    'accounts', coalesce((
      select jsonb_agg(jsonb_build_object(
          'id', k.id, 'slug', k.slug, 'name', k.name, 'organizationId', k.organization_id, 'iconKey', k.icon_key,
          'active', k.active and o.active,
          'superAdmin', v_platform or coalesce(om.is_super_admin and om.status = 'active', false),
          'defaultRoleId', m.default_role_id,
          'roles', coalesce((
            select jsonb_agg(jsonb_build_object(
                'id', r.id, 'key', r.key, 'name', r.name, 'isSystem', r.is_system,
                'permissions', (select coalesce(jsonb_agg(rp.permission_key order by rp.permission_key), '[]') from dk_role_permissions rp where rp.role_id = r.id))
              order by r.id = m.default_role_id desc, r.name)
            from dk_member_roles mr join dk_roles r on r.id = mr.role_id
            where mr.kitchen_id = k.id and mr.user_id = v_user.id and m.active
          ), '[]'))
        order by o.name, k.name)
      from dk_kitchens k
      join dk_organizations o on o.id = k.organization_id
      left join dk_organization_members om on om.organization_id = k.organization_id and om.user_id = v_user.id
      left join dk_kitchen_members m on m.kitchen_id = k.id and m.user_id = v_user.id
      where v_platform
         or (om.status = 'active' and (om.is_super_admin or m.active))
    ), '[]')
  );
end;
$function$;

CREATE OR REPLACE FUNCTION public.dk_ga_organizations()
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  perform dk_require_global_admin();
  return (
    select coalesce(jsonb_agg(jsonb_build_object(
        'id', o.id, 'name', o.name, 'slug', o.slug, 'tenantCode', o.tenant_code, 'active', o.active, 'createdAt', o.created_at,
        'country', o.country, 'city', o.city, 'sector', o.sector, 'category', o.category, 'taxId', o.tax_id,
        'plan', jsonb_build_object('key', s.plan_key, 'name', p.name, 'status', s.status, 'trialEndsAt', s.trial_ends_at),
        'admin', jsonb_build_object('id', ow.id, 'name', ow.full_name, 'email', ow.email, 'activated', ow.auth_user_id is not null),
        'accounts', (select count(*) from dk_kitchens k where k.organization_id = o.id),
        'users', (select count(*) from dk_organization_members m where m.organization_id = o.id),
        'pendingUsers', (select count(*) from dk_organization_members m where m.organization_id = o.id and m.status = 'pending'),
        'lastActivityAt', (select max(a.created_at) from dk_audit_log a where a.organization_id = o.id),
        'featuresOffered', (select coalesce(jsonb_agg(f.key order by f.sort_order), '[]') from dk_features f
                            where f.active and dk_feature_available(o.id, f.key)),
        'aiFeatures', (select coalesce(jsonb_agg(f.key order by f.sort_order), '[]') from dk_features f
                       where f.category = 'ai' and f.active and dk_feature_available(o.id, f.key)),
        'aiRuns30d', (select count(*) from dk_ai_insights i join dk_kitchens k on k.id = i.kitchen_id
                      where k.organization_id = o.id and i.created_at >= now() - interval '30 days'))
      order by o.created_at desc), '[]')
    from dk_organizations o
    left join dk_subscriptions s on s.organization_id = o.id
    left join dk_plans p on p.key = s.plan_key
    left join dk_users ow on ow.id = o.owner_user_id);
end;
$function$;

CREATE OR REPLACE FUNCTION public.dk_ga_create_organization(p_name text, p_sector text, p_category text, p_admin_name text, p_admin_email text, p_plan text, p_country text DEFAULT 'CO'::text, p_city text DEFAULT NULL::text, p_phone text DEFAULT NULL::text, p_tax_id text DEFAULT NULL::text, p_confirm_similar boolean DEFAULT false)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public', 'extensions'
AS $function$
declare
  v_check jsonb;
  v_email text := lower(btrim(coalesce(p_admin_email, '')));
  v_admin_name text := btrim(coalesce(p_admin_name, ''));
  v_me uuid := dk_current_profile_id();
  v_plan dk_plans;
  v_owner uuid;
  v_auth uuid;
  v_existing boolean := false;
  v_result record;
  v_token text;
begin
  perform dk_require_global_admin();
  v_check := dk_ga_check_new_organization(p_name, v_email, p_tax_id);
  if not (v_check ->> 'emailValid')::boolean then raise exception 'El correo del administrador no es válido'; end if;
  if char_length(v_admin_name) not between 2 and 80 then raise exception 'El nombre del administrador debe tener entre 2 y 80 caracteres'; end if;
  if v_check -> 'user' ->> 'ownsOrganization' is not null then
    raise exception 'Ese correo ya administra la organización «%»: una persona solo crea una organización', v_check -> 'user' ->> 'ownsOrganization';
  end if;
  if not coalesce((v_check -> 'user' ->> 'active')::boolean, true) then
    raise exception 'Ese usuario está desactivado en Quanela';
  end if;
  if jsonb_array_length(v_check -> 'similarOrganizations') > 0 and not coalesce(p_confirm_similar, false) then
    raise exception 'SIMILAR_ORGANIZATION: ya existe una organización con ese nombre o NIT';
  end if;
  select * into v_plan from dk_plans where key = p_plan;
  if not found then raise exception 'Plan desconocido: %', p_plan; end if;

  -- The Organization Admin: their existing profile, the login they already have, or a new pending profile.
  select id into v_owner from dk_users where lower(email) = v_email limit 1;
  if v_owner is not null then
    v_existing := true;
  else
    select id into v_auth from auth.users where lower(email) = v_email limit 1;
    insert into dk_users (auth_user_id, full_name, email, active) values (v_auth, left(v_admin_name, 80), v_email, true) returning id into v_owner;
    v_existing := v_auth is not null;
  end if;

  select * into v_result
  from dk_provision_organization(v_owner, v_me, p_name, p_sector, p_category, v_plan, null, p_city, p_country, p_phone, p_tax_id, null, null, null);

  -- Secure activation: a one-time token (only its hash is stored), 7 days.
  v_token := dk_new_activation(v_result.new_organization_id, v_owner);

  perform dk_log_event('global_admin.organization_created',
    format('Global Admin creó la organización «%s» con %s como administrador', btrim(p_name), v_email),
    v_result.new_organization_id, v_result.new_kitchen_id, 'success', 'global_admin',
    jsonb_build_object('plan', v_plan.key, 'adminEmail', v_email, 'adminExisting', v_existing), v_me, v_result.new_organization_id::text);

  return jsonb_build_object(
    'organizationId', v_result.new_organization_id,
    'organizationSlug', (select slug from dk_organizations where id = v_result.new_organization_id),
    'tenantCode', (select tenant_code from dk_organizations where id = v_result.new_organization_id),
    'accountSlug', v_result.new_kitchen_slug,
    'adminProfileId', v_owner,
    'adminEmail', v_email,
    'adminName', (select full_name from dk_users where id = v_owner),
    'adminHasLogin', exists (select 1 from dk_users where id = v_owner and auth_user_id is not null),
    'plan', v_plan.name,
    'status', 'pending_activation',
    'createdAt', (select created_at from dk_organizations where id = v_result.new_organization_id),
    'token', v_token);
end;
$function$;
